### ISSUE TITLE
should be possible to install the plugin on the server

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/data4dappl#10]
### Reproduction
* `ssh odata@odata.org.il`
* `. ckan/bin/activate`
* `pip install -e 'git+https://github.com/OriHoch/data4dappl.git#egg=ckanext-odata_org_il&subdirectory=ckan/ckanext-odata_org_il'`

#### expected
* install the plugin

#### actual
* permissions error
```
Exception:
Traceback (most recent call last):
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/pip/req.py", line 1139, in prepare_files
    _make_build_dir(self.build_dir)
  File "/home/ubuntu/ckan/local/lib/python2.7/site-packages/pip/req.py", line 1527, in _make_build_dir
    os.makedirs(build_dir)
  File "/home/ubuntu/ckan/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/ubuntu/ckan/build'
```

**Comment by OriHoch** [comment]
works

there is a script on the server - odata_update.sh - which updates the plugin installation
